# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171116_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
