# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171116_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
