# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171119_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
