# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20171120_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
