# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171120_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
