# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
