# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_post_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
