# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171116_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
