# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_galleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
