# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_special_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
