# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171120_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_css',
            field=models.TextField(blank=True, verbose_name='Special CSS'),
        ),
    ]
