# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20171120_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
